/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds
 */

plugins {
    java
}

tasks.test {
    useJUnitPlatform()
}

repositories {
    mavenCentral()
    jcenter()
}

dependencies {
    implementation("io.vertx:vertx-core:3.9.2")
    implementation("io.vertx:vertx-codegen:3.9.2")
    implementation("io.netty:netty-transport-native-epoll:4.1.51.Final:linux-x86_64")

    implementation("io.vertx:vertx-micrometer-metrics:3.9.2")

    // test
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.5.2")
    testImplementation("org.assertj:assertj-core:3.12.0")
    testImplementation("io.vertx:vertx-junit5:3.9.2")
}

